### ISSUE TITLE
how to pause session & later continue session

### ISSUE THREAD

**Issue by sc20099** [ishristov/bitcoin-private-key-fixer#10]
i have 5 parameters missing, it took 2 hrs to complete 1 %..

how to pause session & continue later??

**Comment by ishristov** [comment]
There is not a pause & resume functionality. And if you are running the script & writing in github at the same time on the same device, that means you are not following the instructions because you are connected to the internet and I'd consider the private key compromised. I wouldn't pause it at that time and I'd keep it running. Then if the private key is restored, move the funds immediately. It would be better to have a faster CPU and run the script there but it's too late now. Let it run and hope for the best. And keep in mind it could find the private key before reaching 100% - it could happen at any time between 0 and 100%. 100% means all possible combinations have been checked, but your key may appear earlier.

**Comment by sc20099** [comment]
Thanks :) it just using 50% of cpu not 100% 
But anyway am keeping my pc on or again i have to restart..
Its a really nice work you have done..
